### ISSUE TITLE
Mapping custom profile field

### ISSUE THREAD

**Issue by fajnzilberg** [LafColITS/Moodle-auth_casattras#33] opened 2021-07-19 13:28 UTC
We got an question regarding this plugin.

We tried to map CAS fields to Moodle custom profile fields, but it does not seem to be able to map the information correctly. We can see that the data is being send. When we pick a Moodle standard field it is being mapped.

I see the question have been already asked but was not treated

We ahve set up the mapping for custom profile field as same as standard field
It works perfectly with standard field but nothing works for custom profile field

Have you any suggestion for us ?

Best regards
bruno

**Comment by merrill-oakland** [comment] 2021-12-03 18:29
So it seems that it can't save the values in the config for custom fields. After you save, it reverts to the defaults for the form fields (including an empty mapping). @mackensen

**Comment by merrill-oakland** [comment] 2021-12-03 18:45
Ok, we are able to progress with the issue we were seeing. If the profile shortname isn't all lowercase, it doesn't save. I actually think this is not this plugin's fault, but in core.

**Comment by mackensen** [comment] 2022-04-14 15:35
I'm testing the plugin against Moodle 4.0. I can't reproduce the issue @ericmerrill mentions, in that I can save mappings regardless of capitalization (maybe it was fixed?). That said, I _can_ reproduce @fajnzilberg's issue in that I cannot get custom data to map correctly.

**Comment by mackensen** [comment] 2022-04-15 15:43
Fixed in v3.9.0 and v4.0.0.

**Closed by mackensen** 2022-04-15 15:43 UTC
